# Generated by Django 5.2.17 on 2026-10-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CultureResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=50, unique=True)),
                ('patient_id', models.CharField(max_length=50)),
                ('patient_age', models.PositiveIntegerField()),
                ('patient_sex', models.CharField(max_length=10)),
                ('specimen', models.CharField(choices=[('Blood', 'Blood'), ('Urine', 'Urine'), ('Sputum', 'Sputum'), ('Pus/Swab', 'Pus/Swab'), ('Other', 'Other')], max_length=50)),
                ('organism', models.CharField(max_length=150)),
                ('culture_result', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=20)),
                ('antibiotic', models.CharField(blank=True, max_length=100)),
                ('susceptibility', models.CharField(blank=True, max_length=20)),
                ('collection_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
