# Generated by Django 5.2.17 on 2026-10-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microbiology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultureresult',
            name='patient_sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cultureresult',
            name='susceptibility',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('I', 'I'), ('R', 'R')], max_length=20),
        ),
    ]
