# Generated by Django 5.2.17 on 2026-10-03 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microbiology', '0002_alter_cultureresult_patient_sex_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultureresult',
            name='antibiotic',
        ),
        migrations.RemoveField(
            model_name='cultureresult',
            name='susceptibility',
        ),
        migrations.AddField(
            model_name='cultureresult',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cultureresult',
            name='organism',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='AntibioticSusceptibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antibiotic', models.CharField(choices=[('Gentamicin', 'Gentamicin'), ('Amikacin', 'Amikacin'), ('Levofloxacin', 'Levofloxacin'), ('Ofloxacin', 'Ofloxacin'), ('Ciprofloxacin', 'Ciprofloxacin'), ('Ceftazidime', 'Ceftazidime'), ('Cefepime', 'Cefepime'), ('Cefotaxime', 'Cefotaxime'), ('Imipenem', 'Imipenem'), ('Meropenem', 'Meropenem'), ('Piperacillin', 'Piperacillin'), ('Piperacillin-tazobactam', 'Piperacillin-tazobactam'), ('Co-trimoxazole', 'Co-trimoxazole'), ('Tetracycline', 'Tetracycline')], max_length=100)),
                ('susceptibility', models.CharField(choices=[('S', 'S'), ('I', 'I'), ('R', 'R')], max_length=1)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='susceptibilities', to='microbiology.cultureresult')),
            ],
        ),
    ]
